# Generated by Django 3.2.4 on 2021-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
